version: '3.1'

services:
  php-fpm:
      build:
        context: ./
        dockerfile: ./php-fpm.docker
      hostname: 'php-fpm'
      networks:
          - internal
      volumes:
          - ./:/app
      working_dir: /app
      restart: on-failure


  nginx:
      build:
        context: ./
        dockerfile: ./nginx.docker
      env_file:
        - .env
      networks:
        - internal
      ports:
        - 8081:80
      volumes:
        - ./:/app
        - ./docker/data/nginx/logs:/var/log/nginx
      environment:
        TZ: 'UTC'
      hostname: 'nginx'
      working_dir: /app
      restart: on-failure


  postgresql:
      image: postgres:9.6
      ports:
        - 127.0.0.1:5433:5432
      hostname: 'postgresql'
      working_dir: /app
      restart: on-failure
      networks:
        - internal
      environment:
        POSTGRES_DB: tasks
        POSTGRES_USER: master
        POSTGRES_PASSWORD: tasks-pass
        TZ: 'UTC'
        PGTZ: 'UTC'
      volumes:
        - ./backup:/root/backup
        - ./docker/data/postgresql:/var/lib/postgresql/data

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28

